apiVersion: batch/v1
kind: Job
metadata:
  name: maniskill-pm-job-short-horizon-grasp-fixed
spec:
  template:
    metadata:
      name: maniskill-pm-pod-short-horizon-grasp-fixed
    spec:
      containers:
        - name: gpu-container
          image: dhbhatt/maniskill-experiments:latest
          command: ["/bin/bash"]
          args: 
            - "-c"
            - |
              cd /workspace/ManiSkill &&
              rm -rf mani_skill/ &&
              git clone --recurse-submodules https://github.com/Pranav-Malpure/Image-based-RL-Manipulation &&
              cd Image-based-RL-Manipulation &&
              git checkout lab_pc &&
              cd ManiSkill &&
              git checkout lab_pc &&
              mv mani_skill/ /workspace/ManiSkill/ &&
              cd .. &&
              python3 sac_rgbd.py --env_id=PickCube-v1 --obs_mode rgb --num_envs=8 --utd=0.5 --buffer_size=250_000 --robot_uids=xarm6_allegro_left --num_eval_envs=8 --control-mode=pd_joint_vel --camera_width=64 --camera_height=64 --total_timesteps=12000000 --eval_freq=10_000
          volumeMounts:
            - mountPath: /pers_vol
              name: pm-slow-vol2
          resources:
            limits:
              nvidia.com/gpu: "1"
              memory: "32G"
              cpu: "4"
            requests:
              nvidia.com/gpu: "1"
              memory: "32G"
              cpu: "4"
      restartPolicy: Never
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 98
              preference:
                matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - "NVIDIA-A100-80GB-PCIe"
                      - "NVIDIA-A100-SXM4-80GB"
                      - "NVIDIA-GeForce-RTX-4090"
                      - "NVIDIA-GeForce-RTX-3090"
            - weight: 1
              preference:
                matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - "NVIDIA-A40"
                      - "NVIDIA-A10"
                      - "Tesla-V100-SXM2-32GB"
            - weight: 1
              preference:
                matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - "NVIDIA_TITAN_RTX"
                      - "NVIDIA-RTX-A6000"
            - weight: 100
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - "ry-gpu-1.sdsc.optiputer.net"
                      - "ry-gpu-2.sdsc.optiputer.net"
                      - "ry-gpu-3.sdsc.optiputer.net"
                      - "ry-gpu-4.sdsc.optiputer.net"
                      - "ry-gpu-5.sdsc.optiputer.net"
                      - "ry-gpu-6.sdsc.optiputer.net"
                      - "ry-gpu-7.sdsc.optiputer.net"
                      - "ry-gpu-8.sdsc.optiputer.net"
                      - "ry-gpu-9.sdsc.optiputer.net"
                      - "ry-gpu-10.sdsc.optiputer.net"
                      - "ry-gpu-11.sdsc.optiputer.net"
                      - "ry-gpu-12.sdsc.optiputer.net"
                      - "ry-gpu-13.sdsc.optiputer.net"
                      - "ry-gpu-14.sdsc.optiputer.net"
                      - "ry-gpu-15.sdsc.optiputer.net"
                      - "k8s-gpu-01.sdsc.optiputer.net"
                      - "k8s-gpu-02.sdsc.optiputer.net"
                      - "k8s-gpu-03.sdsc.optiputer.net"
                      - "k8s-gpu-04.sdsc.optiputer.net"
                      - "k8s-gpu-05.sdsc.optiputer.net"
                      - "k8s-gpu-06.sdsc.optiputer.net"
                      - "k8s-gpu-07.sdsc.optiputer.net"
                      - "k8s-gpu-08.sdsc.optiputer.net"
                      - "k8s-gpu-09.sdsc.optiputer.net"
                      - "k8s-gpu-10.sdsc.optiputer.net"
                      - "k8s-gpu-11.sdsc.optiputer.net"
                      - "k8s-gpu-12.sdsc.optiputer.net"
                      - "k8s-gpu-13.sdsc.optiputer.net"
                      - "k8s-gpu-14.sdsc.optiputer.net"
                      - "k8s-gpu-15.sdsc.optiputer.net"
      volumes:
        - name: pm-slow-vol2
          persistentVolumeClaim:
            claimName: pm-slow-vol2
  backoffLimit: 4  # Limits the number of retries in case the job fails
