apiVersion: v1
kind: Pod
metadata:
  name: maniskill-pm-pod
spec:
  containers:
  - name: gpu-container
    image: dhbhatt/maniskill-experiments:latest
    command: ["/bin/bash", "-c"]
    args: ["-c", "tail -f /dev/null"
        ]
    volumeMounts:
    - mountPath: /pers_vol
      name: pm-slow-vol2
    resources:
      limits:
        nvidia.com/gpu: "2"
        memory: "32G"
        cpu: "16"
      requests:
        nvidia.com/gpu: "2"
        memory: "32G"
        cpu: "12"
  restartPolicy: Never
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: nvidia.com/gpu.product
  #           operator: In
  #           values:
  #           - RTX-3090
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 80
        preference:
          matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - "NVIDIA-A100-80GB-PCIe"
            - "NVIDIA-A100-SXM4-80GB"      
            - "NVIDIA-GeForce-RTX-4090"
            - "NVIDIA-GeForce-RTX-3090"
      - weight: 15
        preference:
          matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - "NVIDIA-A40"
            - "NVIDIA-A10"
            - "Tesla-V100-SXM2-32GB"
      - weight: 5
        preference:
          matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - "NVIDIA_TITAN_RTX"
            - "NVIDIA-RTX-A6000"
      - weight: 100
        preference:
          matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - "ry-gpu-10.sdsc.optiputer.net"
            - "k8s-gpu-03.sdsc.optiputer.net"
  volumes:
    - name: pm-slow-vol2
      persistentVolumeClaim:
        claimName: pm-slow-vol2