apiVersion: batch/v1
kind: Job
metadata:
  name: visweshn-vlm-tdmpc2-rgb-state-sparse-pranav
spec:
  template:
    spec:
      imagePullSecrets:
      - name: dockerhub-viswesh
      restartPolicy: Never
      containers:
      - name: vlm-container
        image: docker.io/visweshnagaswamy/sphere-approx:latest
        imagePullPolicy: Always
        env:
        - name: b3592fd884921171d1224569c36612d0b3604990
          valueFrom:
            secretKeyRef:
              name: wandb-secret
              key: b3592fd884921171d1224569c36612d0b3604990
        - name: PYTHONPATH
          value: /workspace/vlm-manipulation
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: github-secret
              key: GITHUB_PAT
        command: ["/bin/bash", "-c"]
        args:
        - |
          set -eux
          mkdir -p /workspace/vlm-manipulation
          cd /workspace/vlm-manipulation
          if [ ! -d .git ]; then
            git clone https://$GITHUB_PAT@github.com/Viswesh-N/vlm-manipulation.git .
          else
            git stash || true
            git pull origin main || true
          fi

          [ -f requirements.txt ] && pip install -r requirements.txt

          export CUDA_VISIBLE_DEVICES=0
          export HYDRA_FULL_ERROR=1

          python scripts/train/tdmpc2/train.py \
            model_size=5 steps=1000000 seed=2 \
            env_id=PickCube-v1 env_type=gpu num_envs=32 \
            control_mode=pd_joint_vel obs=state include_state=true \
            save_video_local=false wandb=true \
            wandb_project=vlm-manipulation wandb_entity=viswesh-n wandb_name=PushCube-v1-rgb-state-late-fusion-sparse \
            exp_name=tdmpc2-rgb-state \
          | tee /pers_vol/train_logs_$(date +%Y-%m-%d_%H-%M-%S)_rgb-state_quick.log
        volumeMounts:
        - name: pm-slow-vol2
          mountPath: /pers_vol
        resources:
          requests:
            cpu: "16"
            memory: "128Gi"
            nvidia.com/gpu: "1"
          limits:
            cpu: "16"
            memory: "128Gi"
            nvidia.com/gpu: "1"
      volumes:
      - name: pm-slow-vol2
        persistentVolumeClaim:
          claimName: pm-slow-vol2